version: 2
brews:
  - name: gitversion
    homepage: https://github.com/screwdriver-cd/gitversion
    description: A helper for bumping versions via git tags.
    commit_msg_template: "[skip ci] Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      branch: master
    test: |
      system "#{bin}/gitversion", "--version"
builds:
  - binary: gitversion
    # Build for Linux and OSX
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Include the default settings from https://goreleaser.com/#builds
    # Also include static compilation
    ldflags: -s -w -X main.VERSION={{.Version}} -X main.COMMIT={{.Commit}} -X main.DATE={{.Date}} -extldflags "-static"
    # Ensure the binary is static
    env:
      - CGO_ENABLED=0
archives:
    - formats: [ 'binary' ]
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
# Put the packages in the artifacts dir (but it won't eval environment variables)
dist: /sd/workspace/artifacts/dist
