shared:
    image: golang:1.17
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - path: export PATH=$PATH:$GOPATH/bin
            - modverify: go version; go mod verify
            - vet: go vet ./...
            - gofmt: gofmt -l .
            - test-setup: go get gotest.tools/gotestsum@latest
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...
            # Ensure we can compile
            - build: go build -a -o /dev/null
            # Test cross-compiling as well
            - test-release: "curl -sL https://git.io/goreleaser | bash -s -- --snapshot"
    deploy:
        requires: main
        steps:
            - path: export PATH=$PATH:$GOPATH/bin
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go get -t ./...
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
