// Code generated by MockGen. DO NOT EDIT.
// Source: bumper.go

// Package bumper is a generated GoMock package.
package bumper

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBumper is a mock of Bumper interface.
type MockBumper struct {
	ctrl     *gomock.Controller
	recorder *MockBumperMockRecorder
}

// MockBumperMockRecorder is the mock recorder for MockBumper.
type MockBumperMockRecorder struct {
	mock *MockBumper
}

// NewMockBumper creates a new mock instance.
func NewMockBumper(ctrl *gomock.Controller) *MockBumper {
	mock := &MockBumper{ctrl: ctrl}
	mock.recorder = &MockBumperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBumper) EXPECT() *MockBumperMockRecorder {
	return m.recorder
}

// Bump mocks base method.
func (m *MockBumper) Bump(arg0 ...BumpOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Bump", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bump indicates an expected call of Bump.
func (mr *MockBumperMockRecorder) Bump(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bump", reflect.TypeOf((*MockBumper)(nil).Bump), arg0...)
}
