// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bumper

import (
	"github.com/google/wire"
	"github.com/screwdriver-cd/gitversion/git"
)

// Injectors from wire.go:

func NewBumper() Bumper {
	defaultCmdRunner := &git.DefaultCmdRunner{}
	defaultGit := &git.DefaultGit{
		CmdRunner: defaultCmdRunner,
	}
	defaultBumper := &DefaultBumper{
		Git: defaultGit,
	}
	return defaultBumper
}

// wire.go:

var DefaultSet = wire.NewSet(wire.Struct(new(DefaultBumper), "*"), wire.Bind(new(Bumper), new(*DefaultBumper)))

var buildSet = wire.NewSet(
	DefaultSet, git.DefaultSet,
)
