# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitversion < Formula
  desc "A helper for bumping versions via git tags."
  homepage "https://github.com/screwdriver-cd/gitversion"
  version "1.1.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.11/gitversion_darwin_arm64"
      sha256 "e0d2d14a39d1f9e5b0a848f6405e3413a654f7348552043f7efd3dd4c346fc32"

      def install
        bin.install "gitversion_darwin_arm64" => "gitversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.11/gitversion_darwin_amd64"
      sha256 "22c573d69a9e0ec7691f2c652f8c7e634c9a890448912e0f4844b08e1b4b592d"

      def install
        bin.install "gitversion_darwin_amd64" => "gitversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.11/gitversion_linux_amd64"
      sha256 "0fe82e6989f05be43006ef03133870516095ce6f69badd6480d4fc77c5bd89f5"

      def install
        bin.install "gitversion_linux_amd64" => "gitversion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.11/gitversion_linux_arm64"
      sha256 "edaaa63efd317ae6ac53bdf084bd11434aee77bf1bdcdc4a3cd11233bafe39f3"

      def install
        bin.install "gitversion_linux_arm64" => "gitversion"
      end
    end
  end

  test do
    system "#{bin}/gitversion", "--version"
  end
end
