# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitversion < Formula
  desc "A helper for bumping versions via git tags."
  homepage "https://github.com/screwdriver-cd/gitversion"
  version "1.1.30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.30/gitversion_darwin_amd64"
      sha256 "fb4e64e8e338acb3e464bd22808c085c432451278ebe196eb8d725dc8f3729e5"

      def install
        bin.install "gitversion_darwin_amd64" => "gitversion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.30/gitversion_darwin_arm64"
      sha256 "5fd2af7199d4c96fcfad5d8bae8cc549e8611e1b6dec48ad53b390ecee46d5f8"

      def install
        bin.install "gitversion_darwin_arm64" => "gitversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.30/gitversion_linux_amd64"
      sha256 "c53c7aa589fe98275cb252ad98be7d34aa63846d88135b842aac79b0ea352f57"
      def install
        bin.install "gitversion_linux_amd64" => "gitversion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.30/gitversion_linux_arm64"
      sha256 "f4d145d52979d06380e3cca7c1d534989c2491efe85903d974d7983cdbcfd5ba"
      def install
        bin.install "gitversion_linux_arm64" => "gitversion"
      end
    end
  end

  test do
    system "#{bin}/gitversion", "--version"
  end
end
