# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitversion < Formula
  desc "A helper for bumping versions via git tags."
  homepage "https://github.com/screwdriver-cd/gitversion"
  version "1.1.28"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.28/gitversion_darwin_amd64"
      sha256 "de5f7d48b200f94e9dee3413faaf060f9fa06dec2f248083bd1ac64cf4faf92a"

      def install
        bin.install "gitversion_darwin_amd64" => "gitversion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.28/gitversion_darwin_arm64"
      sha256 "3848100552c5e5056806dc12d09c80116fe4bfdceda9a84b5447fe8b5bdefcd3"

      def install
        bin.install "gitversion_darwin_arm64" => "gitversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.28/gitversion_linux_amd64"
      sha256 "fad54d70aa8cd114079624243014a3e5d34e435bc5ad9bcc0a4206df4c2d2e2c"
      def install
        bin.install "gitversion_linux_amd64" => "gitversion"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.28/gitversion_linux_arm64"
      sha256 "690e54caf9ac488636f186e8407ea020e9a21d744df57b895e724f356d8cdef6"
      def install
        bin.install "gitversion_linux_arm64" => "gitversion"
      end
    end
  end

  test do
    system "#{bin}/gitversion", "--version"
  end
end
